#pragma once

#define WIFI_SSID "YOUR_WIFI_NAME"
#define WIFI_PASSWORD "YOUR_WIFI_PASSWORD"

#define SUPABASE_URL "https://yfnirgvfpxgxkdgcfbgy.supabase.co"
#define SUPABASE_KEY "YOUR_SUPABASE_PUBLISHABLE_KEY"

#define DEVICE_ID "esp32-s3-bmp280-01"
#define DEVICE_TOKEN "YOUR_DEVICE_TOKEN"
#define UPLOAD_INTERVAL_MS 30000

#define STATUS_LED_PIN 21
#define STATUS_LED_COUNT 1
#define STATUS_LED_BRIGHTNESS 40

#define TEMPERATURE_OFFSET_C 0.0
